### PR TITLE
Akka-2.5 / Scala 2.13

### PR DESCRIPTION
**Pull request by fabianhjr**

### CODE REVIEW

**Comment by fabianhjr** [comment]
There are still some issues and testing to be done.

The first of the Components test doesn't pass, it is the only one that doesn't.

**Comment by vic** [comment]
Closes #6

**Comment by vic** [comment]
Hello @timcharper,

We've been trying to upgrade this project to at least `akka 2.5` as a first step to later upgrade to current `akka 2.6`.

As @fabianhjr commented, we've tried to re-implement the `BundlingBuffer` component but we are a bit stuck on a failing test (all other tests are green). 

Could you please review the changes, particularly on `BundlingBuffer` and perhaps enlighten us on what we are missing ?

Thank you.

**Comment by vic** [comment]
Good news! All tests green now thanks to @davoclavo

**Comment by vic** [comment]
@timcharper, this branch is now ready for review :)

**Comment by vhnguyenae** [comment]
hi can this PR be merged?
I'm interested since I want to migrate my project to scala 2.13 and I need this to use with [op-rabbit-akka-stream](https://github.com/pjfanning/op-rabbit) 2.13 :-)

**Comment by davoclavo** [comment]
@vhnguyenae hopefully we get to merge this, meanwhile you can use our published artifact on jitpack: 
using sbt:

```
    resolvers += "jitpack" at "https://jitpack.io"

    libraryDependencies += "com.github.deal-engine.acked-stream" %% "acked-streams" % "8f17c92"
```

**Comment by snovgorodtsev-zz** [comment]
Hello @davoclavo ! Just wondering if you're also planning to publish `op-rabbit` Scala 2.13 version somewhere? ;-)

**Comment by davoclavo** [comment]
@snovgorodtsev Hello, we indeed have a version published for scala 2.13 in our company's fork ([link to branch here](https://github.com/deal-engine/op-rabbit/tree/acked-streams-scala-2.13))

```
 resolvers += "jitpack" at "https://jitpack.io"

 libraryDependencies += "com.github.deal-engine.op-rabbit" %% "op-rabbit-core" % "a6f2dea2"
```

EDIT: I updated the version as it was incorrect

**Comment by fabianhjr** [comment]
Thanks for the merge timcharper! UWU

**Comment by snovgorodtsev-zz** [comment]
Hey @fabianhjr ! Do you mind to publish a new version, please? Thanks.

**Comment by fabianhjr** [comment]
@snovgorodtsev I cannot publish a new version.

**Comment by snovgorodtsev-zz** [comment]
Oh sorry I meant @timcharper of course :)

**Pull request merged**
